# T-WEB

version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend