# T-WEB

version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: ""
        MONGO_INITDB_ROOT_PASSWORD: ""